#!/bin/bash

# Prompt the user to enter the number of elements
echo -n "Enter the number of elements in the array: "
read n

# Declare an array
declare -a array

# Input array elements
echo "Enter the elements of the array:"
for ((i = 0; i < n; i++))
do
    read array[i]
done

# Sort the array in descending order using Bubble Sort
for ((i = 0; i < n - 1; i++))
do
    for ((j = 0; j < n - i - 1; j++))
    do
        if [ ${array[j]} -lt ${array[j+1]} ]; then
            # Swap elements
            temp=${array[j]}
            array[j]=${array[j+1]}
            array[j+1]=$temp
        fi
    done
done

# Display the sorted array
echo "Array elements in descending order:"
for element in "${array[@]}"
do
    echo "$element"
done
